<a href="https://colab.research.google.com/github/nada598/My_portfolio/blob/main/Python_101_Python_Libraries_for_Data_Analysis_Numpy_and_Pandas_ipynb_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [92]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
import numpy as np
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax

# Let's define a one-dimensional array
list_1=[50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [93]:
# Let's create a numpy array from the list "my_list"
my_numpy_array=np.array(list_1)
my_numpy_array


array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [94]:
type(my_numpy_array)

numpy.ndarray

In [95]:
# Multi-dimensional (Matrix definition)
my_matrix=np.array([[2,5,8],
[7,3,6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1:
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3]
[4 3 2 2]]
```

In [96]:
x=np.array([[3,7,9,3],[4,3,2,2]])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [97]:
# "rand()" uniform distribution between 0 and 1
x =np.random.rand(20)
x

array([0.27525642, 0.04497305, 0.66789884, 0.27833121, 0.43793948,
       0.24717448, 0.85222044, 0.73946768, 0.26708214, 0.35868097,
       0.04796793, 0.11959209, 0.72360367, 0.36192979, 0.79879061,
       0.81553871, 0.0320606 , 0.38832753, 0.62771087, 0.78257241])

In [98]:
# you can create a matrix of random number as well
x= np.random.rand(3,3)
x

array([[0.05149076, 0.47441726, 0.25108544],
       [0.59066826, 0.87938688, 0.82804141],
       [0.39164864, 0.24288223, 0.54891194]])

In [99]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x

37

In [100]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,100,15)
x

array([10, 69, 71, 18, 66, 89, 30, 95, 74, 90, 94, 19, 66, 58, 84])

In [101]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [102]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [103]:
# Matrix of ones
x=np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [104]:
# Array of zeros
x=np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x=int(input("Enter positive number: "))
x=np.random.randint(0,x,(1,10))
x

Enter positive number: 30


array([[ 0,  5, 12,  4,  8,  3, 14,  3, 20, 22]])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [16]:
# np.arange() returns an evenly spaced values within a given interval
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Add 2 numpy arrays together
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
squared=x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
sqrt= np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
z=np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [22]:
X=np.array([5, 7, 20])
Y=np.array([9, 15, 4])
dist=np.sqrt(X**2+Y**2)
dist

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [23]:
my_numpy_array=np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [24]:
# Access specific index from the numpy array
my_numpy_array[2]

6

In [25]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[2:5]

array([6, 2, 8])

In [26]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[2:5]=9
my_numpy_array

array([ 3,  5,  9,  9,  9, 10, 20, 50])

In [27]:
# Let's define a two dimensional numpy array
matrix=np.random.randint(1,10,(4,4))
matrix

array([[3, 3, 9, 6],
       [7, 6, 7, 6],
       [4, 1, 2, 6],
       [1, 3, 1, 4]])

In [28]:
# Get a row from a mtrix
matrix[0]

array([3, 3, 9, 6])

In [29]:
# Get one element
matrix[0][1]

3

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [30]:
#matrix=np.random.randint(1,100,(5,5)) is right but is not required by challange
matrix=np.array([[2, 30, 20, -2 ,-4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
matrix[4]=0
matrix

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [31]:
matrix=np.random.randint(1,10,(5,5))
matrix

array([[1, 1, 2, 8, 9],
       [3, 2, 8, 9, 9],
       [7, 3, 2, 4, 6],
       [3, 3, 7, 4, 1],
       [2, 2, 4, 8, 1]])

In [32]:
new_matrix=matrix[matrix>7]
new_matrix

array([8, 9, 8, 9, 9, 8])

In [33]:
# Obtain odd elements only
new_matrix=matrix[matrix%2==1]
new_matrix

array([1, 1, 9, 3, 9, 9, 7, 3, 3, 3, 7, 1, 1])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [34]:
x=np.array([[2,30,20, -2, -4],
    [3, 4 , 40, -3 ,-2],
    [-3, 4, -6 ,90, 10],
    [25, 45 ,34, 22 ,12],
    [13, 24 ,22, 32 ,37]])
x[x<0]=0
x[x%2==1]=-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

In [35]:
# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [36]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python).
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [37]:
import pandas as pd

In [38]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
#  I have inforamtion about client bank/client name money
bank_client_df=pd.DataFrame({'Bank Client ID':[111,222,333,444],
                             'Bank client Name':['Chanel','Steve','Mitch','Ryan'],
                             'Net Worth[$]':[3500,29000,10000,2000],
                             'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank client Name  Net Worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [39]:
# Let's obtain the data type
type(bank_client_df)

pandas.core.frame.DataFrame

In [40]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank client Name  Net Worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4

In [41]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank client Name  Net Worth[$]  Years with bank
2             333            Mitch         10000                9
3             444             Ryan          2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [42]:
portfolio_df=pd.DataFrame({'stock ticker symbols':['MSFT',"APPL",'AMZN'],'price per share [$]':[200,500,30],'Number of stock':[3,4,9]})

In [43]:
portfolio_df

stock ticker symbols  price per share [$]  Number of stock
0                 MSFT                  200                3
1                 APPL                  500                4
2                 AMZN                   30                9

In [44]:
#Calculate the total value of the porfolio including all stocks
stocks_dollar_value=portfolio_df['price per share [$]']*portfolio_df['Number of stock']
stocks_dollar_value.sum()

2870

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [45]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df=pd.read_html('http://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [46]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [47]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [48]:
us_retirement=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
us_retirement[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [49]:
# Let's define a dataframe as follows:
bank_client_df=pd.DataFrame({'Bank Client ID':[111,222,333,444],
                             'Bank client Name':['Chanel','Steve','Mitch','Ryan'],
                             'Net Worth[$]':[3500,29000,10000,2000],
                             'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank client Name  Net Worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [50]:
# Pick certain rows that satisfy a certain criteria
df_loyal=bank_client_df[bank_client_df['Years with bank']>=5]
df_loyal

Bank Client ID Bank client Name  Net Worth[$]  Years with bank
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [51]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank client Name  Net Worth[$]  Years with bank
0           Chanel          3500                3
1            Steve         29000                4
2            Mitch         10000                9
3             Ryan          2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
- What is the combined networth for all customers with 5000+ networth?

In [52]:
df_loyal_high=bank_client_df[bank_client_df['Net Worth[$]']>=5000]
df_loyal_high

Bank client Name  Net Worth[$]  Years with bank
1            Steve         29000                4
2            Mitch         10000                9

In [53]:
# combined networth for all customers with 5000+ networth
df_loyal_high['Net Worth[$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [54]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [55]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake)
def networth_update(balance):
  # y a fixed value of 20%  (1.2) indicate that you incrase 20%
  return balance*1.2

In [56]:
# You can apply a function to the DataFrame
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [57]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [58]:
# Define a function that triples the stock prices and adds $200
def stock_price(price):
  return price*3+200

In [59]:
# Apply the function to the DataFrame
results=bank_client_df['Net worth [$]'].apply(stock_price)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [60]:
# Calculate the updated total networth of all clients combined
results.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [61]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [62]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [63]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [64]:
# Set inplace = True to ensure that change has taken place in memory
bank_client_df.sort_values(by='Years with bank',inplace=True)

In [65]:
# Note that now the change (ordering) took place
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [66]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [67]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C0','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']},index=[0,1,2,3])



In [68]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [69]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'C':['C4','C5','C6','C7'],
                  'D':['D4','D5','D6','D7']},index=[4,5,6,7])

In [70]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [71]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                  'C':['C8','C9','C10','C11'],
                  'D':['D8','D9','D10','D11']},index=[8,9,10,11])

In [72]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [73]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [112]:
# Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'],
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [113]:
#Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
raw_data = {'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'],
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}

Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [115]:
#Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
            'Annual Salary': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


Bank Client ID Annual Salary [$/year]
0              1                    NaN
1              2                    NaN
2              3                    NaN
3              4                    NaN
4              5                    NaN
5              6                    NaN
6              7                    NaN
7              8                    NaN
8              9                    NaN
9             10                    NaN

In [117]:
#Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
bank_df_all=pd.concat([Bank_df_1,Bank_df_2])
bank_df_all

Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [118]:
#Merge client names and their newly added salary information using the 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Last Name Annual Salary [$/year]
0              1      Nancy        Rob                    NaN
1              2       Alex        Ali                    NaN
2              3       Shep     George                    NaN
3              4        Max      Mitch                    NaN
4              5      Allen      Steve                    NaN
5              6       Bill  Christian                    NaN
6              7       Dina         Mo                    NaN
7              8      Sarah      Steve                    NaN
8              9    Heather        Bob                    NaN
9             10      Holly   Michelle                    NaN

In [119]:
#Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'],
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [120]:
# Add this new dataframe to the original dataframe 'bank_df_all'.
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name Annual Salary [$/year]
0              1      Nancy        Rob                    NaN
1              2       Alex        Ali                    NaN
2              3       Shep     George                    NaN
3              4        Max      Mitch                    NaN
4              5      Allen      Steve                    NaN
5              6       Bill  Christian                    NaN
6              7       Dina         Mo                    NaN
7              8      Sarah      Steve                    NaN
8              9    Heather        Bob                    NaN
9             10      Holly   Michelle                    NaN
0             11         Ry        Aly                   1000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION:
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3]
[4 3 2 2]]
```

In [75]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [76]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 30


array([20,  7,  1, 22,  7, 10, 11, 26, 16,  5])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [77]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [78]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [79]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [80]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [81]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40],
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [82]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [83]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

[                                        Year of birth  \
 0                                      1937 and prior   
 1                                                1938   
 2                                                1939   
 3                                                1940   
 4                                                1941   
 5                                                1942   
 6                                             1943-54   
 7                                                1955   
 8                                                1956   
 9                                                1957   
 10                                               1958   
 11                                               1959   
 12                                     1960 and later   
 13  Notes: 1. Persons born on January 1 of any yea...   
 
                                                   Age  
 0                                                  65  
 1            

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
- What is the combined networth for all customers with 5000+ networth?

In [84]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

Bank client ID Bank Client Name  Net worth [$]  Years with bank
1             222            Steve          29000                4
2             333            Mitch          10000                9

In [85]:
df_high_networth['Net worth [$]'].sum()

39000

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [86]:
def networth_update(balance):
    return balance * 3 + 200

In [87]:
# You can apply a function to the DataFrame
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
3     6200
2    30200
Name: Net worth [$], dtype: int64

In [88]:
results.sum()

134300

PROJECT SOLUTION:

In [89]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'],
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'],
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers
# Note that data obtained is for all clients with IDs 1 to 10
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [90]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'],
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [91]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000